# Generated by Django 2.2.4 on 2019-08-27 20:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190827_2027'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='credit',
            options={'verbose_name': '积分流水', 'verbose_name_plural': '积分流水'},
        ),
        migrations.AddField(
            model_name='credit',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='credit_record', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='credit',
            table='ly_credit',
        ),
    ]
