# Generated by Django 2.2.4 on 2019-08-07 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Banner',
            new_name='BannerInfo',
        ),
    ]
