# Generated by Django 2.2.4 on 2019-08-07 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20190807_2053'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bannerinfo',
            old_name='create_time',
            new_name='created_time',
        ),
        migrations.RenameField(
            model_name='bannerinfo',
            old_name='update_time',
            new_name='updated_time',
        ),
        migrations.RenameField(
            model_name='navinfo',
            old_name='create_time',
            new_name='created_time',
        ),
        migrations.RenameField(
            model_name='navinfo',
            old_name='update_time',
            new_name='updated_time',
        ),
    ]
