# Generated by Django 2.2.4 on 2019-08-27 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usercoupon',
            options={'verbose_name': '我的优惠券', 'verbose_name_plural': '我的优惠券'},
        ),
    ]
