# Generated by Django 2.2.4 on 2019-08-14 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courselesson',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='courselessons', to='courses.Course', verbose_name='课程名称'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='courselesson',
            name='is_show_list',
            field=models.BooleanField(default=False, verbose_name='是否展示到列表页中'),
        ),
    ]
