# Generated by Django 2.2.4 on 2019-08-16 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20190815_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_video',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='course', verbose_name='封面视频'),
        ),
    ]
