# Generated by Django 2.2.4 on 2019-08-19 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_courseexpire'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseexpire',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='课程价格'),
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='当前价格表示购买视频的永久价格，如果没有永久购买的价格的话，则默认为0，不需要填写', max_digits=6, verbose_name='课程原价'),
        ),
    ]
